<Project>
  <ItemGroup>
    <PackageVersion Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.*" />
    <PackageVersion Include="FluentValidation.AspNetCore" Version="11.*" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.*" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.*" />
    <PackageVersion Include="QRCoder" Version="1.*" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.*" />
    <PackageVersion Include="Serilog.Sinks.MSSqlServer" Version="6.*" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.*" />
  </ItemGroup>
</Project>
