// <auto-generated />
using System;
using ChangeManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeManagement.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729011609_InitialCreateSqlServer")]
    partial class InitialCreateSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChangeManagement.Api.Models.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineeringRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EngineeringRequestId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.EngineeringRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApplicableToChemicalOrMaterials")
                        .HasColumnType("bit");

                    b.Property<int?>("ApprovedByCooUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CheckedByDeptHeadUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CheckedByQaUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChemicalClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChemicalInventorySystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChemicalLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CooComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CooDecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CooDecision")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Demerit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptHeadComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeptHeadDecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptHeadDecision")
                        .HasColumnType("int");

                    b.Property<int>("Division")
                        .HasColumnType("int");

                    b.Property<string>("ErNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaterialDisposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("PresentDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QaComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("QaDecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QaDecision")
                        .HasColumnType("int");

                    b.Property<bool>("ReasonAlternativeSourcing")
                        .HasColumnType("bit");

                    b.Property<bool>("ReasonCostDown")
                        .HasColumnType("bit");

                    b.Property<bool>("ReasonOthers")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonOthersText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResubmitDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("SafetyComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafetyDataSheet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SafetyDecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SafetyDecision")
                        .HasColumnType("int");

                    b.Property<int?>("SampleQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestLotCodeSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestLotDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestLotType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBySafetyUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ErNumber", "SubmissionNumber")
                        .IsUnique();

                    b.ToTable("EngineeringRequests");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.ErAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineeringRequestId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsImage")
                        .HasColumnType("bit");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineeringRequestId");

                    b.ToTable("ErAttachments");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.ErComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EngineeringRequestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineeringRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("ErComments");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.ErSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastSequence")
                        .HasColumnType("int");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("YearMonth")
                        .IsUnique();

                    b.ToTable("ErSequences");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("LookupItems");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.EmailLog", b =>
                {
                    b.HasOne("ChangeManagement.Api.Models.EngineeringRequest", "EngineeringRequest")
                        .WithMany("EmailLogs")
                        .HasForeignKey("EngineeringRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EngineeringRequest");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.EngineeringRequest", b =>
                {
                    b.HasOne("ChangeManagement.Api.Models.User", "Requester")
                        .WithMany("Requests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.ErAttachment", b =>
                {
                    b.HasOne("ChangeManagement.Api.Models.EngineeringRequest", "EngineeringRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("EngineeringRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EngineeringRequest");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.ErComment", b =>
                {
                    b.HasOne("ChangeManagement.Api.Models.EngineeringRequest", "EngineeringRequest")
                        .WithMany("Comments")
                        .HasForeignKey("EngineeringRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChangeManagement.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EngineeringRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.EngineeringRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("ChangeManagement.Api.Models.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
